import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import Navbar from "@/app/components/navbar/Navbar";
import ToasterProvider from "@/app/components/providers/ToasterProvider";
import ModalsProvider from "@/app/components/providers/ModalsProvider";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToasterProvider />
        <ModalsProvider />
        <Navbar />
        {children}
      </body>
    </html>
  )
}

